eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: hall-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.9.223:3306/mooc_meetingfilm?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: ablejava
    filters: log4j,wall,mergeStat

server:
  port: 8401
logging:
  config: classpath:logback.xml

#  mybatis.config-location=classpath:mybatis.xml
#  mybatis.mapper-locations=classpath:mapper/*.xml
mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.mooc.meeting.film.backendfilm.entity

#  mybatis.type-aliases-package=com.mooc.meeting.film.user.entity